controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# app_logout est le nom de la route définie dans secutity.yaml
# elle n'est pas associée à un traitement mais interceptée par le composant de sécurité
app_logout:
    path: /logout
